name: moor_state_management
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get_it: ^7.2.0
  moor: ^4.4.1
  path: ^1.8.0
  path_provider: ^2.0.2
  sqlite3_flutter_libs: ^0.5.0

dev_dependencies:
  build_runner: ^2.1.1
  flutter_test:
    sdk: flutter
  lint: ^1.6.0
  moor_generator: ^4.4.1

flutter:
  uses-material-design: true
